site_name: 乐湖修远
site_url: https://mydomain.org/mysite
ite_author: PanosPeng
# 代码仓库信息
repo_name: PanosPeng/xiuyuan # 仓库名称
repo_url: https://github.com/PanosPeng/xiuyuan.github.io.git # 仓库地址

# 版权信息
copyright: Copyright &copy; 2024 ~ now |   PanosPeng
# 主题配置
theme:
  name: material
  language: zh
  logo: image/lehu_icon.png # 默认路径在docs/下
  favicon: image/lehu_icon.png
  features: # 功能  
    - announce.dismiss # 可以叉掉公告的功能
    - content.code.copy # 复制代码按钮
    - content.tooltips # 不太清楚呢这个
    # - header.autohide # 自动隐藏header
    - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # 顶栏颜色
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono
favicon: assets/favicon.png # 网站图标 似乎不需要管
icon: # 一些用到的icon
  logo: logo
  previous: fontawesome/solid/angle-left
  next: fontawesome/solid/angle-right
  tag:
    default-tag: fontawesome/solid/tag
    hardware-tag: fontawesome/solid/microchip
    software-tag: fontawesome/solid/laptop-code

# 导航树 - 请按照我的做法来做，否则可能无法正常工作。引号可以省略。开头的点和斜杠也可以省略 ("./HOME/about.md" 或 Home/about.md) 。注意，导航树这里的文件名是 filename.md 这样的，但在文件夹中，它实际上被命名为 filename.en.md 和 filename.zh.md。我猜测默认是英文，所以, index.en.md 和 index.md 是一样的。i18n插件会自动识别文件名，然后根据文件名的后缀来切换语言。所以，如果你想添加一个新页面，你需要添加两个文件，一个是 filename.en.md，另一个是 filename.zh.md。其中，filename.en.md 也可以被命名为 filename.md，但是 filename.zh.md 不能被命名为 filename.md，否则会导致无法识别。
# 
nav: 
  - 首页: 
      - "index.md"
      - 关于: "./HOME/about.md"
  - CS: 
      - "./CS/CS.md"

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
# 社交角标