site_name: My docs
site_url: https://mydomain.org/mysite
ite_author: PanosPeng
# 代码仓库信息
repo_name: PanosPeng/xiuyuan # 仓库名称
repo_url: https://github.com/PanosPeng/xiuyuan.github.io.git # 仓库地址

# 版权信息
copyright: Copyright &copy; 2024 ~ now |   PanosPeng
theme:
  name: material
  language: zh

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
# 社交角标